# Generated by Django 2.2.4 on 2019-10-04 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=30, verbose_name='Nome do departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero do Documento')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo do Processo')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Pessoa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo do Processo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appcorrecao.Departamento')),
                ('interessada', models.ManyToManyField(related_name='Interessada', to='appcorrecao.Pessoa')),
                ('investigada', models.ManyToManyField(related_name='Investigada', to='appcorrecao.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcorrecao.Pessoa')),
                ('matricula', models.CharField(max_length=30, verbose_name='Matricula do Funcionario')),
            ],
            bases=('appcorrecao.pessoa',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcorrecao.Documento')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
            ],
            bases=('appcorrecao.documento',),
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcorrecao.Documento')),
                ('justificativa', models.CharField(max_length=50, verbose_name='Justificativa')),
                ('prazo_anterior', models.DateField(verbose_name='Data Inicial')),
                ('prazo_seguinte', models.DateField(verbose_name='Data Nova')),
            ],
            bases=('appcorrecao.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_origem', models.DateField(verbose_name='Data Origem')),
                ('data_destino', models.DateField(verbose_name='Data Destino')),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_destino', to='appcorrecao.Departamento')),
                ('departamento_origem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento_origem', to='appcorrecao.Departamento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appcorrecao.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appcorrecao.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appcorrecao.Funcionario'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appcorrecao.Documento')),
                ('data_envio', models.DateField(verbose_name='Data de envio')),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appcorrecao.Departamento')),
            ],
            bases=('appcorrecao.documento',),
        ),
    ]
